### ISSUE TITLE
popup opening with uniquex.co link

### ISSUE THREAD

**Issue by muhammadalizia** [summitsingh/youtube-mp3-downloader#1]
where ever you click on page... a popup is oppening with the link http://findbetterresults.com/?dn=uniquex.co&pid=9PO755G95

how to disable this?

**Comment by summitsingh** [comment]
I will check the issue and update you. Thanks.

**Comment by summitsingh** [comment]
Please update _templates/default/layers/site_header.php_ file to resolve this error.
